export const headers = [
  "Application Type",
  "Name",
  "Email",
  "Phone",
  "Type of Business",
  "Description of Business",
  "Business Activity",
  "Date of Incorporation",
  "Adddress",
  "Address2",
  "City",
  "State",
  "Pincode",
  "Entity Branch Details",
  "Pan Card",
  "Apply Date",
  "NoYears",
  "Business Name",
  "leadSource",
];


const LeadExcelTemplate = [
  {
    "Application Type": "IEC Registration",
    Name: "D365 SOLUTIONS PVT LTD",
    Email: "revanthitrs@gmail.com",
    Phone: "9542911555",
    "Type of Business": "Private Limited",
    "Description of Business": "",
    "Business Activity": "Service Provider",
    "Date of Incorporation": "6/18/2019",
    Adddress: "1-37/1114, V K Marakkar Arcade,",
    Address2: "Seaport Airport Road, Thrikkakara,",
    City: "KAKKANAD",
    State: "KERALA",
    Pincode: "682021",
    "Entity Branch Details": "",
    "Pan Card": "AAHCD2989D",
    "Apply Date": "12/14/2022 14:31",
    NoYears: "",
    "Business Name": "",
    leadSource: "FSSAI Copy Website",
  },
  {
    "Application Type": "FSSAI Registration",
    Name: "pradeep",
    Email: "tesspradeepp@gmail.com",
    Phone: "8989898989",
    "Type of Business": "INDIVIDUAL",
    "Description of Business": "Ready-to-eat savouries",
    "Business Activity": "Marketer",
    "Date of Incorporation": "",
    Adddress: "delhi",
    Address2: "delhi",
    City: "delhi",
    State: "HIMACHAL PRADESH",
    Pincode: "110042",
    "Entity Branch Details": "",
    "Pan Card": "",
    "Apply Date": "",
    NoYears: "5 Years",
    "Business Name": "",
    leadSource: "IEC Copy Website",
  },
  {
    "Application Type": "GST Registration",
    Name: "Jasweer kour",
    Email: "graceenterprises86@gmail.com",
    Phone: "9821907974",
    "Type of Business": "Others",
    "Description of Business": "Supplier of Services",
    "Business Activity": "Financial and training",
    "Date of Incorporation": "",
    Adddress: "H.No 63/2B Basai enclave",
    Address2: "Ratlam",
    City: "Gurugram",
    State: "Haryana",
    Pincode: "122001",
    "Entity Branch Details": "",
    "Pan Card": "",
    "Apply Date": "",
    NoYears: "",
    "Business Name": "Grace enterprises",
    leadSource: "GST Copy Website",
  },
];

export default LeadExcelTemplate;